### PR TITLE
Ls/fixed rosenbrock

### PR DESCRIPTION
**Pull request by lsoucasse**
This work implements the Rosenbrock timestepping scheme for computation of stellar evolution quantities with a fixed time grid (though increasing timestep).

To determine the time grid, I ran the adaptive Rosenbrock scheme and plot the time step as a function of time. I roughly obtained a power law dAge = 0.1 Age^0.75 (Myr). I added a capping to a maximum time step of 50 Myr for further accuracy.

This time step is now set as the default one. I added a test but kept the one using the ForwardEuler scheme.

### CODE REVIEW

**Comment by lsoucasse** [comment]
> Fast work, thanks @lsoucasse. Does the Rosenbrock method roughly reproduce the results of the Euler method?

Yes, you can actually compare them as I kept same input for the two tests (Rosenbrock/Euler). Highest differences are of the order of 5% for XUV fluxes as spotted earlier with the adaptive Rosenbrock.

**Comment by lsoucasse** [comment]
Actually I also ran the Proteus test (physical integration) and only escape rate is affected (which makes sense).

**Comment by lsoucasse** [comment]
> I agree that that makes sense. If we run PROTEUS with the updated version of MORS, will it then automatically use this new integrator by default?

Yes, I switch this new time scheme as the default as discussed this morning. I already have a proteus branch with updated test values. I will open a PR once pyPI release is published.

**Review by nichollsh — APPROVED** [review]

**Comment by lsoucasse** [comment]
If you want to run with previous time stepping scheme use:
`    params = mors.NewParams()
     params['TimeIntegrationMethod'] = 'ForwardEuler'
     star = mors.Star(Mstar=inp[0], Omega=inp[1], params = params)`

**Pull request merged**
