### PR TITLE
Adjust access to synthesis functions.

### PR DESCRIPTION
**Pull request by lsoucasse**
Adjust access to synthesis functions so that we can use whole track data generated on the proteus side.

### CODE REVIEW

**Comment by lsoucasse** [comment]
I don't understand why the test is failing. The data download part has not been touched. Any idea @nichollsh ?

**Comment by nichollsh** [comment]
It's not immediately obvious to me but I will check on my machine locally to see if this is reproducible.

**Comment by nichollsh** [comment]
I've noticed that sometimes the OSF download fails, so maybe it's that actually (see https://github.com/FormingWorlds/PROTEUS/issues/206)

**Comment by nichollsh** [comment]
@lsoucasse I didn't change any code but re-ran the failing test, and now it seems to be okay. I think this is mostly certainly the same problem as https://github.com/FormingWorlds/PROTEUS/issues/206

**Review by nichollsh — APPROVED** [review]
Looks good! Fine to merge as long as the tests pass this time

**Pull request merged**
